### ISSUE TITLE
TransmitterError: A transmitter already exists

### ISSUE THREAD

**Issue by alessiomarta** [dbbs-lab/bsb-neuron#3]
Trying to simulate a network with both ascending axon to golgi and ascending axon to purkinje yields the following error.

```
Traceback (most recent call last):
  File "/home/alessio/.pyenv/versions/100323/bin/bsb", line 8, in <module>
    sys.exit(handle_cli())
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 10, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 30, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/__init__.py", line 97, in execute_handler
    self.handler(context)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/_commands.py", line 205, in handler
    result = network.run_simulation(sim_name)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/profiling.py", line 157, in decorated
    return f(*args, **kwargs)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/core.py", line 420, in run_simulation
    return adapter.simulate(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulation/adapter.py", line 10, in simulate
    data = self.prepare(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 91, in prepare
    self.create_connections(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 155, in create_connections
    simdata.connections[conn_model] = conn_model.create_connections(
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/connection.py", line 41, in create_connections
    self.create_transmitters(simdata, cs)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/connection.py", line 50, in create_transmitters
    simdata.cells[loc[0]].insert_transmitter(gid, (loc[1], 0), source=self.source)
  File "/home/alessio/.pyenv/versions/3.9.12/envs/100323/lib/python3.9/site-packages/arborize/builders/_neuron.py", line 97, in insert_transmitter
    raise TransmitterError(
arborize.exceptions.TransmitterError: A transmitter already exists with gid 62600

```
I'm running the simulation with one node.

**Comment by Helveg** [comment]
The GID assignment procedure is a bit complicated. Since NEURON uses global state, the first big offset is each simulation that has previously been prepared, stored in the `next_gid` attribute of the adapter, which shouldn't matter much here.

Then a range is allocated for this simulation, equal to the amount of outgoing connections in all the chunks (since BSB transmitters are the presynaptic half of the synapse representation in NEURON sims). The complexity arises because GIDs need to be unique per Section in NEURON, so they have to be deduplicated and mapped. To keep things somewhat efficient, and because spatial resolution on the transmitters isn't usually critical, they are deduplicated per branch on the BSB morphology (even though there could be multiple Sections per branch, that's fine):

```python
    def _map_transmitters(self, simulation, simdata):
        blocks = []
        for cm, cs in simulation.get_connectivity_sets().items():
            pre, _ = cs.load_connections().as_globals().all()
            pre[:, 0] += simdata.cid_offsets[cs.pre_type]
            blocks.append(pre[:, :2])
        if blocks:
            blocks = np.unique(np.concatenate(blocks), axis=0)
```

Here we offset `pre[:, 0] += simdata.cid_offsets[cs.pre_type]` with the offset of the presynaptic cell types, so that if we have multiple transmitters across connection types on the same cellbranch, they will yield the same `(cell, branch)` pair and be deduplicated.

`pre[:, :2]` takes out the cell and branch id, we then take all unique `(cell, branch)` rows across all connections, and assign them a GID:

```python
        return {
            tuple(loc): gid + simdata.alloc[0]
            for gid, loc in zip(itertools.count(), blocks)
        }
```

Something may be going wrong there

**Comment by Helveg** [comment]
The issue was that the same section was being retrieved from the map multiple times, and asked to insert a transmitter. In v3 arborize checked if a transmitter already existed, nooped, and returned the existing transmitter. @alessiomarta I can't find where we fixed this? Could you commit/push/PR this fix so we can close this?
