### ISSUE TITLE
error in creating connections

### ISSUE THREAD

**Issue by danilobenozzo** [dbbs-lab/bsb-neuron#4]
```
Traceback (most recent call last):
  File "/home/neuro_sim1/spack/var/spack/environments/bsb-neuron/.spack-env/view/bin/bsb", line 8, in <module>
    sys.exit(handle_cli())
  File "/home/neuro_sim1/neuron/bsb-core/bsb/cli/__init__.py", line 11, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/cli/__init__.py", line 31, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/cli/commands/__init__.py", line 98, in execute_handler
    self.handler(context)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/cli/commands/_commands.py", line 207, in handler
    result = network.run_simulation(sim_name)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/profiling.py", line 158, in decorated
    return f(*args, **kwargs)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/core.py", line 425, in run_simulation
    return adapter.simulate(simulation)
  File "/home/neuro_sim1/neuron/bsb-core/bsb/simulation/adapter.py", line 35, in simulate
    data = self.prepare(simulation)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/adapter.py", line 86, in prepare
    self.create_connections(simulation)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/adapter.py", line 146, in create_connections
    simdata.connections[conn_model] = conn_model.create_connections(
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/connection.py", line 41, in create_connections
    self.create_transmitters(simdata, cs)
  File "/home/neuro_sim1/neuron/bsb-neuron/bsb_neuron/connection.py", line 50, in create_transmitters
    simdata.cells[gid].insert_transmitter(gid, (loc[1], 0), source=self.source)
KeyError: 60867
```

@Helveg reminder: your suggestion was to avoid cells and only use populations

**Comment by Helveg** [comment]
Thanks for reporting the issue. Once I've got all the single cell models running I will implement a fix!

PS: Please use [code block formatting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
