### ISSUE TITLE
Operator < not supported between instances of 'TransceiverModel' and 'TransceiverModel'

### ISSUE THREAD

**Issue by alessiomarta** [dbbs-lab/bsb-neuron#7]
Trying to simulate a network with both ascending axon to golgi and ascending axon to purkinje yields the following error.

```
  File "/home/alessio/.pyenv/versions/100323/bin/bsb", line 8, in <module>
    sys.exit(handle_cli())
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 10, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 30, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/__init__.py", line 97, in execute_handler
    self.handler(context)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/_commands.py", line 205, in handler
    result = network.run_simulation(sim_name)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/profiling.py", line 157, in decorated
    return f(*args, **kwargs)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/core.py", line 420, in run_simulation
    return adapter.simulate(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulation/adapter.py", line 10, in simulate
    data = self.prepare(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 91, in prepare
    self.create_connections(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 151, in create_connections
    self._allocate_transmitters(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 175, in _allocate_transmitters
    simdata.transmap = self._map_transmitters(simulation, simdata)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 179, in _map_transmitters
    for cm, cs in simulation.get_connectivity_sets().items():
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulation/simulation.py", line 121, in get_connectivity_sets
    for model in sorted(self.connection_models.values())
TypeError: '<' not supported between instances of 'TransceiverModel' and 'TransceiverModel'
```

**Comment by alessiomarta** [comment]
Removing `sorted` from line 121 in `bsb/bsb/simulation/simulation.py` yields another error

Traceback (most recent call last):
  File "/home/alessio/.pyenv/versions/100323/bin/bsb", line 8, in <module>
    sys.exit(handle_cli())
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 10, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/__init__.py", line 30, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/__init__.py", line 97, in execute_handler
    self.handler(context)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/cli/commands/_commands.py", line 205, in handler
    result = network.run_simulation(sim_name)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/profiling.py", line 157, in decorated
    return f(*args, **kwargs)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/core.py", line 420, in run_simulation
    return adapter.simulate(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulation/adapter.py", line 10, in simulate
    data = self.prepare(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 91, in prepare
    self.create_connections(simulation)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/adapter.py", line 155, in create_connections
    simdata.connections[conn_model] = conn_model.create_connections(
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/connection.py", line 41, in create_connections
    self.create_transmitters(simdata, cs)
  File "/home/alessio/Documenti/GitHub/bsb_neuron_last/100323/bsb/bsb/simulators/neuron/connection.py", line 50, in create_transmitters
    simdata.cells[loc[0]].insert_transmitter(gid, (loc[1], 0), source=self.source)
  File "/home/alessio/.pyenv/versions/3.9.12/envs/100323/lib/python3.9/site-packages/arborize/builders/_neuron.py", line 97, in insert_transmitter
    raise TransmitterError(
arborize.exceptions.TransmitterError: A transmitter already exists with gid 62600

**Comment by Helveg** [comment]
The GID assignment procedure needs to be deterministic across nodes, which it isn't guaranteed if you removed `sorted`. The original error can be fixed by implementing a deterministic `__lt__` method such as:

```
    def __lt__(self, other):
        try:
            return self.name < other.name
        except Exception:
            return True
```

**Comment by alessiomarta** [comment]
This solves `TypeError: '<' not supported between instances of 'TransceiverModel' and 'TransceiverModel'`, but the TransmitterError. I assumed they were related, but apparently they are not. I'm opening another issue in Arborize.

**Comment by alessiomarta** [comment]
By the way, I'm testing it with only one node; The GID assignment procedure shouldn't be a problem.

**Comment by Helveg** [comment]
Ah, then the GID assignment procedure must be assigning overlapping ranges, let's continue that on your other issue. I assume you've fixed this on your `devices` branch? You can keep collecting fixes for the NEURON adapter there and we can merge it as a bigger NEURON improvements branch :)

**Comment by Helveg** [comment]
@alessiomarta did you end up implementing this `__lt__` method? Where can I find the fix?

**Comment by Helveg** [comment]
@alessiomarta ping, is this still occurring, can we close this?

**Comment by alessiomarta** [comment]
To my knowledge it's not occurring anymore. Maybe we should ask Danilo for confirmation.

**Comment by Helveg** [comment]
If this was usually occurring during a regular simulation workflow then the tests cover this, and the issue is resolved. Feel free to reopen, also @danilobenozzo, if the issue reappears :)
